# Generated by Django 4.0.4 on 2022-06-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messeges',
            new_name='Messages',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='messege',
            new_name='message',
        ),
    ]
