# Generated by Django 4.0.4 on 2022-05-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_dislike_alter_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userprofile')),
                ('dislike', models.ManyToManyField(related_name='comment_dislikes', to='blog.userprofile')),
                ('like', models.ManyToManyField(related_name='comment_likes', to='blog.userprofile')),
            ],
        ),
    ]
