# Generated by Django 4.0.4 on 2022-06-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_post_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='comment_title',
        ),
    ]
