# Generated by Django 4.0.4 on 2022-06-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_body_comment_comment_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_title',
            new_name='title',
        ),
    ]
