# Generated by Django 4.0.4 on 2022-05-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_comment'),
        ('blog', '0015_comment_post_comment'),
    ]

    operations = [
    ]
