# Generated by Django 4.0.4 on 2022-05-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_merge_20220530_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
