# Generated by Django 4.0.4 on 2022-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_dislike_likes_value_remove_likes_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likes',
        ),
    ]
